# Generated by Django 4.1 on 2022-08-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cats', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Фото кота',
                'verbose_name_plural': 'Фото котов',
            },
        ),
    ]
